name: Auto Push

on:
  schedule:
    - cron: '0 9 * * *' # هر روز ساعت 9 صبح UTC
  workflow_dispatch: # امکان اجرا دستی

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set git identity
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Make changes
        run: |
          date >> autopush.log

      - name: Commit changes
        run: |
          git add .
          git commit -m "Auto push $(date)"
          git push
